FROM fedora:38

ARG osbuild_composer_version=*

RUN \
    dnf in -y \
        $(echo "/rpms/osbuild-composer-dnf-json-${osbuild_composer_version}-1.*.x86_64.rpm") \
        $(echo "/rpms/osbuild-composer-core-${osbuild_composer_version}-1.*.x86_64.rpm") \
        $(echo "/rpms/osbuild-composer-worker-${osbuild_composer_version}-1.*.x86_64.rpm") \
        $(echo "/rpms/osbuild-composer-${osbuild_composer_version}-1.*.x86_64.rpm") \
        libxcrypt-compat && \
        dnf clean all

COPY \
    ./entrypoint.py /opt/entrypoint.py

# XXX why is this state directory not created by the RPM?
RUN \
    mkdir -p /var/lib/osbuild-composer/

ENTRYPOINT ["python3", "/opt/entrypoint.py"]
