FROM registry.fedoraproject.org/fedora:40

ARG osbuild_composer_version=*
ARG osbuild_version=*

RUN \
    dnf in -y \
        $(echo "/rpms/osbuild-composer-dnf-json-${osbuild_composer_version}-1.*.x86_64.rpm") \
        $(echo "/rpms/osbuild-composer-worker-${osbuild_composer_version}-1.*.x86_64.rpm") \
        $(echo "/rpms/python3-osbuild-${osbuild_version}-1.*.noarch.rpm") \
        $(echo "/rpms/osbuild-${osbuild_version}-1.*.noarch.rpm") \
        $(echo "/rpms/osbuild-*-${osbuild_version}-1.*.noarch.rpm") \
        qemu-img \
        libxcrypt-compat && \
        dnf clean all

RUN \
    mkdir -p /var/cache/osbuild-worker/output && \
    mkdir -p /var/lib/osbuild-composer/ && \
    mkdir -p /run/osbuild-composer/

ENTRYPOINT ["/usr/libexec/osbuild-composer/osbuild-worker"]
