FROM fedora:36

ARG osbuild_composer_version=*

RUN \
    dnf in -y \
        $(echo "/rpms/osbuild-composer-dnf-json-${osbuild_composer_version}-1.*.x86_64.rpm") \
        $(echo "/rpms/osbuild-composer-worker-${osbuild_composer_version}-1.*.x86_64.rpm") \
        libxcrypt-compat && \
        dnf clean all

ENTRYPOINT ["/usr/libexec/osbuild-composer/osbuild-worker"]
